### ISSUE TITLE
"or" operator violates DM4, DeMorgan's law

### ISSUE THREAD

**Issue by rockwalrus** [DavidKinder/Inform6#112]
The Inform compiler treats
```
~~(a > b or c)
```
and
```
a <= b or c
```

exactly the same. Similar statements are true for every conditional operator. The user cannot easily anticipate which member of each pair is the one that will get compiled correctly.

**Comment by erkyrath** [comment]
I'm not sure what you're saying? The "or" alternative syntax is a little unintuitive if you think of it as boolean logic, but the manual is clear that 

    if (alpha == 3 or 4) print "Equal to either alternative";

    if (alpha ~= 5 or 7 or 9) print "Different from all alternatives";

**Comment by rockwalrus** [comment]
Hopefully this example will clarify what I mean. There are eight expressions with comparison operators in the example below. Four compile correctly and four do not. Part of the reason for this is that both expressions on each line compile to exactly the same code even though they should not.
```
[ Main;
#ifdef TARGET_GLULX;
  @setiosys 2 0;
  glk($002F, glk($0023, 0, 0, 0, 3, 0));
#endif;

  print "2 <= 1 or 3: ", 2 <= 1 or 3, "   @@126@@126(2 >  1 or 3): ", ~~(2 >  1 or 3), "^";
  print "2 <  1 or 3: ", 2 <  1 or 3, "   @@126@@126(2 >= 1 or 3): ", ~~(2 >= 1 or 3), "^";
  print "2 >= 1 or 3: ", 2 >= 1 or 3, "   @@126@@126(2 <  1 or 3): ", ~~(2 <  1 or 3), "^";
  print "2 >  1 or 3: ", 2 >  1 or 3, "   @@126@@126(2 <= 1 or 3): ", ~~(2 <= 1 or 3), "^";
];
```

**Comment by erkyrath** [comment]
Thanks, I understand now.

I'm going to avoid arguing about what's "correct", because there are two intuitive rules we could follow:

`(X <= A or B)` is equivalent to `(X < A or B) || (X == A or B)`
`(X <= A or B)` is equivalent to `~~(X > A or B)`

These can't both be true as written. But you can make an argument for both -- both add an "or B" clause to an obviously true rule. The compiler goes with the second rule, as you've demonstrated.

Note that we've already accepted that:

`(X ~= A or B)` is equivalent to `~~(X == A or B)`

This is both documented and practical (it's the useful definition of `(X ~= A or B)`). So there's some consistency in the current handling of `(X <= A or B)`. 

On the other hand, I agree that I like the first rule better. I have a stronger sense that `<` is "almost the same as" `<=`.

On the third hand, the current behavior has been around a long time and maybe some code relies on it.

On the fourth hand, using these operators (`<` `>` `<=` `>=`) with "or" isn't all that useful in the first place. I can't think of a situation where I'd do it. This means that backwards compatibility is less important, but then changing the behavior is *also* less important.

The only comment from the manual is:

> Or you might want to use
> `if (x > 100 or y) ...`
> to test whether x is bigger than the minimum of 100 and y.

This is kind of contrived.

**Comment by erkyrath** [comment]
Some forum discussion: https://intfiction.org/t/next-steps-for-inform-6-compiler/51008/84

My conclusions (from that thread):

The current behavior is not confusing for positive-sense comparisons ( `x == 4 or 5;` `rock in sack or chest` .) Nor is it confusing for negative-sense comparisons ( `x ~= 4 or 5;` `rock notin sack or chest` .) There’s only one sensible way to read these expressions and that’s how the compiler understands them.

The behavior of `x < y or z` takes some thought. (For a start, I have to switch to variables, because writing `x < 4 or 5` is pointless!) But this form is both documented in the manual and consistent with `x == y or z` in an obvious way. This extends directly to `x > y or z` .

Things only get weird because the compiler treats `<=` and `>=` as negative-sense comparisons, and that’s not how we normally think of them.

So my conclusion is:

* Leave the current behavior;
* Generate a warning for `<= or` and `>= or` only;
* Document.

**Comment by DavidKinder** [comment]
We now have warnings for `(x <= y or z)` and `(x >= y or z)`. I'm closing this as that should be sufficient: we are not going to change the behaviour of existing code at this point.
