### ISSUE TITLE
Remove MAX_IDENTIFIER_LENGTH limit

### ISSUE THREAD

**Issue by erkyrath** [DavidKinder/Inform6#176]
Allow identifiers of any length.

(Request from Graham, tagged "non-urgent".)

We use this as an array size in various places, so there will have to be more memlists. Tedious but not complicated.

(Can we use asprintf() for error messages, instead of fixed-size buffers? Will that wreck the poor C99 users?)

**Comment by DavidKinder** [comment]
> Can we use asprintf() for error messages, instead of fixed-size buffers? Will that wreck the poor C99 users?

(Assuming you mean C89 users.) asprintf() is a GNU-ism, I think, rather than something codified by C99. It's certainly possible to provide an implementation of asprintf() that works on Microsoft Visual C++ in a few lines, so with a few macros we can cover Linux and Windows, but I don't think that would work for old compiler users. Maybe just a fall-back to a fixed size buffer?
