### ISSUE TITLE
Object -> ignores object which has a name reference to parent

### ISSUE THREAD

**Issue by fredrikr** [DavidKinder/Inform6#49]
Consider this code:

```
Object Kitchen "Kitchen"
  with description "Nice kitchen",
  has light;
  
Object bag "bag" selfobj
  has container open;

Object -> hammer "hammer";

```

This places the hammer in the kitchen. I think this is weird and inconvenient behaviour, but maybe it's intentional. And I realize that changing it could break existing code.

**Comment by erkyrath** [comment]
It's not ignoring it. The algorithm is: for an object with N arrows, it searches backwards through the list of defined objects for an object with a (true) depth of N-1. That becomes the parent.

So, for example, you could do this:

```
Object Kitchen;
Object bag selfobj;
Object -> -> hammer;
```

The hammer winds up inside the bag, because the bag's depth is 1.

I agree that this rule gets weird when the `->` notation intersects the older `Object foo parent` notation. There are weird cases even if you stick to arrows. E.g.:

```
Object Kitchen;
Object -> bag;
Object Bathroom;
Object -> -> hammer;
```

The hammer still winds up inside the bag -- not intuitive.

However, I'm not sure any alternative algorithm is free of weird corner cases. And, as you say, old code may rely on the current behavior.

**Comment by fredrikr** [comment]
Ah, that makes sense then, in a weird way.
