### ISSUE TITLE
Option to break on first error

### ISSUE THREAD

**Issue by Kroc** [DavidKinder/Inform6#91]
Sometimes you only care about the first error and everything else is junk you have to scroll through. This is particularly the case on mobile devices and where you might be using the terminal in VSCode and not have a large amount of screen space.

**Comment by erkyrath** [comment]
The problem is that the first error isn't always enough information.

Does your device let you do "inform | head -10"?

**Comment by Kroc** [comment]
Unfortunately no! The EPOC32 C library is so limited & janky that you cannot scroll the output at all. The OS was designed GUI first, so doesn't have a built in shell, and the one that is available is very, very basic being not much more than a means of executing CLI apps with parameters.

I don't enough C/C++ to be able to wrap the C code to use the native C++ UI, so it's not something I'm going to be able to solve any time soon :/

**Comment by erkyrath** [comment]
My feeling is that this is too narrow and hacky a feature to be worth the complication. Because:

- Platforms with limited screen space are not a big user base.
- Inform can generate a lot of output in a lot of ways. (Trace directives, `-a`, `-h`, ...) There's never going to be a way to make them all useful without scrolling.
- As I said, there's no guarantee that the first error is enough information.

**Comment by erkyrath** [comment]
Also, I just noticed a MAX_ERRORS constant in header.h. You could recompile with that set to a lower number.

**Comment by Kroc** [comment]
Good point, thanks
